workflows:
  ios-workflow:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - manual_code_signing
      vars:
        APP_ID: "uk.asherlewis.theforge"
      xcode: latest
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Initialize Keychain
        script: keychain initialize
        
      # --- NEW LOGIC: Force-Reformat Key ---
      - name: Reconstruct Key (Python)
        script: |
          python3 -c "
          import os
          import base64

          try:
              # 1. Get the Base64 string from the environment
              b64_input = os.environ.get('IOS_AUTH_KEY', '').strip()
              
              # 2. Decode it to text
              decoded_str = base64.b64decode(b64_input).decode('utf-8')
              
              # 3. CLEANING: Remove existing headers, footers, and ALL whitespace/newlines
              # This gives us just the raw key data, ensuring no 'Windows' characters survive
              raw_body = decoded_str.replace('-----BEGIN PRIVATE KEY-----', '')
              raw_body = raw_body.replace('-----END PRIVATE KEY-----', '')
              raw_body = ''.join(raw_body.split()) 

              # 4. REBUILDING: Create a perfect PEM structure
              # Header + Key split into 64-char lines + Footer
              final_key = '-----BEGIN PRIVATE KEY-----\n'
              for i in range(0, len(raw_body), 64):
                  final_key += raw_body[i:i+64] + '\n'
              final_key += '-----END PRIVATE KEY-----\n'

              # 5. Write to file
              with open('/tmp/apikey.p8', 'w') as f:
                  f.write(final_key)
                  
              print('✅ Key reconstructed with perfect formatting.')
              
          except Exception as e:
              print(f'❌ Error: {e}')
              exit(1)
          "
      # -------------------------------------

      - name: Set up code signing settings
        script: |
          app-store-connect fetch-signing-files "$APP_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "@/tmp/apikey.p8"
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Build IPA
        script: >-
          xcode-project build-ipa
          --workspace "ios/App/App.xcworkspace"
          --scheme "App"
          --config Release
    publishing:
      app_store_connect:
        api_key: "@/tmp/apikey.p8"
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
