workflows:
  ios-workflow:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - manual_code_signing
      vars:
        APP_ID: "uk.asherlewis.theforge"
      xcode: latest
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Initialize Keychain
        script: keychain initialize
      - name: Reconstruct Private Key
        script: |
          # 1. Decode the Base64 variable to a temporary file
          echo "$IOS_AUTH_KEY" | base64 -D > /tmp/temp_decode.p8
          
          # 2. Extract ONLY the raw secret key code (remove headers, footers, spaces, newlines)
          # We use 'grep -v' to remove the BEGIN/END lines, and 'tr' to delete formatting
          RAW_SECRET=$(cat /tmp/temp_decode.p8 | grep -v "PRIVATE KEY" | tr -d '\r\n ')
          
          # 3. Rebuild the file from scratch with perfect Apple formatting (64-char width)
          echo "-----BEGIN PRIVATE KEY-----" > /tmp/apikey.p8
          echo "$RAW_SECRET" | fold -w 64 >> /tmp/apikey.p8
          echo "-----END PRIVATE KEY-----" >> /tmp/apikey.p8
          
          # 4. Verify the file looks correct in the logs (for safety)
          echo "✅ Key Reconstructed. First line:"
          head -n 1 /tmp/apikey.p8

      - name: Set up code signing settings
        script: |
          app-store-connect fetch-signing-files "$APP_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "@/tmp/apikey.p8"
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Build IPA
        script: >-
          xcode-project build-ipa
          --workspace "ios/App/App.xcworkspace"
          --scheme "App"
          --config Release
    publishing:
      app_store_connect:
        api_key: "@/tmp/apikey.p8"
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
